name: Test and Release

on:
  workflow_dispatch:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'main' || github.ref_name == 'next' }}
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_branch || github.ref_name }}

      - name: Retrieve additional tag data
        run: git fetch --tags --force

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install Packages
        run: yarn install

      - name: Compile the Package
        run: yarn build:all

      - name: Install semantic-release dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPMB_TOKEN }}
        run: npm i -g semantic-release semantic-release-monorepo @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/npm @semantic-release/github

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPMB_TOKEN }}
        run: npx semantic-release -e semantic-release-monorepo
